language: node_js
node_js:
- '7'
cache:
  yarn: true
  directories:
  - "~/.cache/yarn"
before_script:
- npm run build
script:
- npm run lint
- npm test
after_success:
- npm run deploy:demo
deploy:
  provider: npm
  email: kamataryo@users.noreply.github.com
  api_key:
    secure: ei0jWQ7m2bl0wdcQpeYb2dn+Mslg+2sDK0Kk9++1qMaXsEM7a78cTXLegGTZDDDdda4UXnz3ct4ZlArnDVQYKk/4nidMfoH3AYJ8ynVX6SOy1Gr456xXehdGJO0zyhjkfJWEg0w7hP44E62B/h6JDX7qoEYmraLQo74jyf6pPc/NI4/zLz42YbqtxgC7UDr3In0aTsQMHY4HQXN8fs3deY3O8igvgp86Pa8ABM4Bgj9KZ0NIa6eVXadOzdCGQa4+DpjEeZB0NTsUm/oNu0oOYzNqAep6cs/dXl3qV+br+IouSVxZ3d3TtDeWsdSzFMxhRjtCjIhITJKjJTfi0HP88thhvzt4PeZTHNfsCUvDPwKU3I5xrngHrN6LkrIYvORelnjHYhU6j0ULzEl4swHy9dwWpfnbog7e6y7WnnUhs6L3RdoQsv9BZ7LYLPhxBkRKkIaRd8aLFBbv0Lj0U7nAUAN+18nVJqcbcIT5DzmTo7RgItWCieRdvmHJGS37b1EQaViigiuuOBzDA5LNynkPfJANcS5R02oKeptu0Xc5SNNWoJMVgXJdgbobbck6cRgwIww2LQ/dIpL0Qqb2+9Uxz0Mvjbn58Be/CJy+6mV4t51++y8CopBwqjW32hTlZoTcfSe7uCOYJ8jI+drm+2LzCRuYYaS56aCbHCoaN708KGE=
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - GIT_USER: Travis CI
  - GIT_EMAIL: kamataryo@users.noreply.github.com
  - GH_REF: github.com/kamataryo/react-prez.git
  - secure: "y3K6Mpew/qpy8B5cfxP4rUXk2kAWJNFwp8Ot0B/sgL7gLpyNVu5qsxpmZiIM9EL9rFfKkrmfXAHFcqTSVVOIAyKTMcNHMNVL8rJj2/Gk0stELGJbdAOQz19Bisp6YCURM+DbtI7StTwMt+sF8pslv6E3Z3L7oF+NiaOeyVZcZxPQidCfS9SVE2sAnri/0AZ4Y8tpQubpoVVfM6AjvBVUslzlgh6WIEYHdV6e2fRpIv7xLyZ79KpgbuyvDevFZRJVLxFdihOsTIO/rzjEOg8aR0SHmKbx+BdZRxquySihYNfLNRRyzoTZU4XSdqzYETrkQVO+wNWMFDvlqpFWYpoMSjGrnwSaZRK1pJEjLPROgz7RZi/wK4xarUZrfxzf7KSN3wmYBEqcZM68QmBkHYuo4s2KnGYayo1RJ6kdd0drIYyHBpSG5UFaKbaggg/FnkQInc7UMlRKh76/u1OYi6OQgLK8m4s1XXEDTo7LulOb8ZTZAvG8Kel+UMAg7cSJVEFaqeqOZEh4Qvz07b+LJvPAv1zk1t4qHSl+oZKPwbP7w+hXJhE1bve80/LCRyeiAYAhzKe1izybF+Z5TaHL+9KCXmkqJJuHf0orVmw82oFYQIb6CpSdma6v+E4T4n+NkNBQbiVHOB1yXBoIfWaV8jvr4Xu4RWLjmUWX/v25oZa/Iys="
