language: node_js
node_js:
- '7'
cache:
  yarn: true
  directories:
  - "~/.cache/yarn"
before_script:
- npm run build
script:
- npm run lint
- npm test
after_success:
- npm run deploy:demo
deploy:
  provider: npm
  email: kamataryo@users.noreply.github.com
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: nBQ4DAZ0Lkxp8dHx32ETqhfcBJN00rxMWhk6FutJzYZujMQcQm28PiAyHUYc4h8/GiW6M73jNQKmKrfjUPR/spfyuMGwnhKfEbwy/ya+S8Eo6p1RnKRMmiDvaF7HA6qKU6eO+sO5iDuooNoQL5UoD3moCRBgE//dS9F+pvU4mIHDYBZdckq+MQZ1oxjRm7PZk/eYbHQjEXKY7rbwl6NMe5mkjCjdxZQunxJFyKGiEhsPXMh4/ND6g5JQbZ6kn1rAfyEgW7bATCTmsi4pivj+8rfZcU2nQofanI/FiOrKQ/JDZZkQDZFOmAMpkY8zzLKBQd2FWVNoozCFn/1WkoObXLDftfLwK69B5JKjftY/dtZzaLEmFawmhmKIw6bWt1P7MQ/7JXCIugkOa4JaKi3FVILB67ZMaP5QJaZgKLF7BCK/xDNIFZLln5d0pO60sJYxL8Syb+aoYduAVnqQuMdkvc98eo24TMK9FeF3nGNIIwL6uZ56BG8O/26Xgo5CtC8WyL8/C9ouQgODX6ngZ9pqAQmA2S5vJ4J03p4FkATTPQpRBzV+sz3us0RHnmHZpyPDqUvxuDX3Xi5+fxfrdtt9PXv8atDnROD901aUVx7HEw0AaS8IUjAzSw6v50tOOZ2r4dGgniCb0qL1lDrzQ10oS3e8o5pjnY9Kpvo81sFpMxE=
env:
  global:
  - GIT_USER: Travis CI
  - GIT_EMAIL: kamataryo@users.noreply.github.com
  - GH_REF: github.com/kamataryo/react-prez.git
  - secure: y3K6Mpew/qpy8B5cfxP4rUXk2kAWJNFwp8Ot0B/sgL7gLpyNVu5qsxpmZiIM9EL9rFfKkrmfXAHFcqTSVVOIAyKTMcNHMNVL8rJj2/Gk0stELGJbdAOQz19Bisp6YCURM+DbtI7StTwMt+sF8pslv6E3Z3L7oF+NiaOeyVZcZxPQidCfS9SVE2sAnri/0AZ4Y8tpQubpoVVfM6AjvBVUslzlgh6WIEYHdV6e2fRpIv7xLyZ79KpgbuyvDevFZRJVLxFdihOsTIO/rzjEOg8aR0SHmKbx+BdZRxquySihYNfLNRRyzoTZU4XSdqzYETrkQVO+wNWMFDvlqpFWYpoMSjGrnwSaZRK1pJEjLPROgz7RZi/wK4xarUZrfxzf7KSN3wmYBEqcZM68QmBkHYuo4s2KnGYayo1RJ6kdd0drIYyHBpSG5UFaKbaggg/FnkQInc7UMlRKh76/u1OYi6OQgLK8m4s1XXEDTo7LulOb8ZTZAvG8Kel+UMAg7cSJVEFaqeqOZEh4Qvz07b+LJvPAv1zk1t4qHSl+oZKPwbP7w+hXJhE1bve80/LCRyeiAYAhzKe1izybF+Z5TaHL+9KCXmkqJJuHf0orVmw82oFYQIb6CpSdma6v+E4T4n+NkNBQbiVHOB1yXBoIfWaV8jvr4Xu4RWLjmUWX/v25oZa/Iys=
