language: node_js
node_js:
- '7'
cache:
  yarn: true
  directories:
  - "~/.cache/yarn"
before_script:
- npm run build
script:
- npm run lint
- npm test
after_success:
- npm run deploy:demo
deploy:
  provider: npm
  email: kamataryo@users.noreply.github.com
  api_key:
    secure: ei0jWQ7m2bl0wdcQpeYb2dn+Mslg+2sDK0Kk9++1qMaXsEM7a78cTXLegGTZDDDdda4UXnz3ct4ZlArnDVQYKk/4nidMfoH3AYJ8ynVX6SOy1Gr456xXehdGJO0zyhjkfJWEg0w7hP44E62B/h6JDX7qoEYmraLQo74jyf6pPc/NI4/zLz42YbqtxgC7UDr3In0aTsQMHY4HQXN8fs3deY3O8igvgp86Pa8ABM4Bgj9KZ0NIa6eVXadOzdCGQa4+DpjEeZB0NTsUm/oNu0oOYzNqAep6cs/dXl3qV+br+IouSVxZ3d3TtDeWsdSzFMxhRjtCjIhITJKjJTfi0HP88thhvzt4PeZTHNfsCUvDPwKU3I5xrngHrN6LkrIYvORelnjHYhU6j0ULzEl4swHy9dwWpfnbog7e6y7WnnUhs6L3RdoQsv9BZ7LYLPhxBkRKkIaRd8aLFBbv0Lj0U7nAUAN+18nVJqcbcIT5DzmTo7RgItWCieRdvmHJGS37b1EQaViigiuuOBzDA5LNynkPfJANcS5R02oKeptu0Xc5SNNWoJMVgXJdgbobbck6cRgwIww2LQ/dIpL0Qqb2+9Uxz0Mvjbn58Be/CJy+6mV4t51++y8CopBwqjW32hTlZoTcfSe7uCOYJ8jI+drm+2LzCRuYYaS56aCbHCoaN708KGE=
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - GIT_USER: Travis CI
  - GIT_EMAIL: kamataryo@users.noreply.github.com
  - GH_REF: github.com/kamataryo/react-prez.git
  - secure: Dy+rIwOZMh6ZVMMJf/5Mz4N9LX0ycYbMwVI8pWwVl4YL/R0Zfx9etaGdhqWD5w3u/bn/tH6trT9P8FuNIII24gbS5tlbVO+iz5ZCPI+pzfNn1P8t9FfpoU6GyNwWwsKjX6/s148TRQzv7MJpsWZZuEMvhMahGSY7OqXho0tB1f2HrKt8j0DvpJ7I+HHBPq14r3e++gYxtvLthOrY8V7ZDyfJkmmwIhvlu1qze6TwYIwleyERmF6DmF2IrsnQ1FBlU/k6KlZPyLIBQStAydPUwLcvrtznKRO05hRKY7OKx7gsy9Gxy67ZynH2cyjNeBoYfptyeZp6dbS10KvsomMofke3hfbYra9GYlaEL/tHmKVilmPR3zhyou+lgIY1fEY8jZUfPRmA5AXGDFah6vN6905Hn5TN8CqbmKchyUUTBRUcjDxuvpI+nKHqbgAxv9l8nn5N2mUU9r5YLhX/xLBETh1AeBZhPB8JTYRfJP4bU/PL2XFkyVWbz8RKp2/QOhnzYWtn93tC35Ritd0CrMYXWferJ3dUj884OCaQHSJRkTLkJiDwaYjGDM29bfUEMhumQ3J4ghMcS0BgmyzyoyyoASy/oheaH9FmrCUjHwTAWRSf3/coh92ricuVsKts+ZvNUzJ6hYwNrVvZS3/BBt8dFXqjGRxzNPwuRKouzqn/rMY=
